### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by staticmade** [CMP-Studio/cmoa-app-cms#2]
As we get ready for public release, we need to update the README file w/ changes & modifications for this version.

**Comment by drewmcd621** [comment]
Hi Jeff,

I've been keeping version changes in the "Release Notes" section:

https://github.com/CMP-Studio/cmoa-app-cms/releases/tag/v3.0

I didn't have any on the 3.0 release, I just updated them.

**Comment by staticmade** [comment]
Cool. But the README should also be updated to reflect that this is now "Carnegie Museums of Art and Natural History" and updated language (removal of "artworks" in favor of "art and specimens") because it's the first thing people see when they visit the repo.

**Comment by staticmade** [comment]
@drewmcd621 after you update README with new language and any config spec updates, can you please file a pull request so your work is folded back into CMOA's repo? Thx.
