### ISSUE TITLE
Error on video upload: Incomplete response received from application

### ISSUE THREAD

**Issue by kulas** [CMP-Studio/cmoa-app-cms#5]
After selecting the file to upload and completion of the upload the browser returns an error screen with the Incomplete response message.

Related?
http://stackoverflow.com/questions/29241053/incomplete-response-received-from-application-from-nginx-passenger

**Comment by RubenSandwich** [comment]
@kulas Can you provide the file that you attempted to upload and which object you attempted to upload it to?

**Comment by RubenSandwich** [comment]
Closing this issue as I now feel that it is resolved.
